version: '3'

x-app-common:
  &app-common
  build: ./fastapi
  command: |
      ./run.sh

services:
  nginx:
    image: nginx:latest
    ports:
      - 6002:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/static:/app/static

    depends_on:
      - app1
      - app2
      - app3

  app1:
    <<: *app-common

  app2:
    <<: *app-common

  app3:
    <<: *app-common